notifications:
  email:
    recipients:
      - pufang@maihaoche.com

language: java

jdk:
  - openjdk8

sudo: false
script:
  - travis_retry mvn -B clean
  - travis_retry mvn -B package jacoco:report coveralls:report